
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emersonandrade
 */
public class ExibirItens extends javax.swing.JFrame {
    
     //referência para a tela de cadastro
    private CadastrarItem telaCadastrarItem;
    
    //array para manter os intens "salvos"
    private ArrayList<Itens> array;
    /**
     * Creates new form ExibirItens
     */
    public ExibirItens() {
        initComponents();
        //inicialização da tela CadastrarItem
        telaCadastrarItem =  new CadastrarItem(this);
        
        this.array = new ArrayList<Itens>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        BtExibir = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtFechar = new javax.swing.JButton();
        BtCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Descrição"
            }
        ));
        jScrollPane2.setViewportView(tabela);

        BtExibir.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        BtExibir.setText("Exibir");
        BtExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExibirActionPerformed(evt);
            }
        });

        BtExcluir.setForeground(new java.awt.Color(204, 0, 0));
        BtExcluir.setText("Excluir");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        BtFechar.setText("Fechar");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });

        BtCadastrar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        BtCadastrar.setForeground(new java.awt.Color(51, 204, 0));
        BtCadastrar.setText("Cadastrar");
        BtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        jLabel1.setText("Tabela de Itens Cadastrados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtExibir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtFechar)
                        .addGap(18, 18, 18)
                        .addComponent(BtCadastrar)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtFechar)
                    .addComponent(BtExcluir)
                    .addComponent(BtExibir))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtFecharActionPerformed

    private void BtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarActionPerformed
        // TODO add your handling code here:
        //torna a tela CadastrarItem visível
            this.telaCadastrarItem.setVisible(true);
            
            //torna esta tela invisível
            this.setVisible(false);
    }//GEN-LAST:event_BtCadastrarActionPerformed

    private void BtExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExibirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionda = tabela.getSelectedRow();
                
        if (linhaSelecionda < 0){
            JOptionPane.showMessageDialog(this, "Selecione uma linha", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else{
            this.telaCadastrarItem.mostrarItem(array.get(linhaSelecionda));
            this.setVisible(false);
        }
    }//GEN-LAST:event_BtExibirActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tabela.getSelectedRow();
        
        if (selectedIndex < 0){
            //nenhuma linha selecionada
            JOptionPane.showMessageDialog(this, "Selecione um item","Aviso",JOptionPane.WARNING_MESSAGE);
        }else{
            //um item está selecionado, então remove
            this.removeItem(selectedIndex);        
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    //adiciona item à tabela
    public void addItem(Itens i){
        this.array.add(i);
        this.addItemTabela(i);
    }
    
    public void addItemTabela(Itens i){
        DefaultTableModel model = (DefaultTableModel)tabela.getModel();
        model.addRow(new Object[]{i.getNome(), i.getDescricao()});
    }
    
    //remove da array
    public void removeItem(int i){
        array.remove(i);
        removeItemTabela(i);
    }
    
    //remove da tabela
    public void removeItemTabela(int i){
        DefaultTableModel model = (DefaultTableModel)tabela.getModel();
        model.removeRow(i);
    }
    
    public void redesenhaTabela(){
        DefaultTableModel model = (DefaultTableModel)tabela.getModel();
        while (model.getRowCount() > 0){
            model.removeRow(0);
        }
        
        for (Itens i : array){
            model.addRow(new Object[]{i.getNome(), i.getDescricao()});
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtExibir;
    private javax.swing.JButton BtFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
